(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/org-mode")
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/org-mode/contrib/lisp")
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/ESS/lisp")

;; Required stuff
(require 'ess-stata-mode)
(require 'org)
(load "ox-bibtex.el")

;; Setup default settings
(setq org-confirm-babel-evaluate nil
      org-src-fontify-natively nil
      org-html-postamble "Generated by %c on %T (%e)"
      org-html-doctype "html5"
      org-html-head "<link rel=\"stylesheet\" type=\"text/css\" href=\"/Users/chl/org/drafts/_assets/worg.css\" />"
      org-html-head-include-default-style nil
      org-html-head-include-scripts nil
      org-export-with-section-numbers nil
      org-html-htmlize-output-type nil
      ess-ask-for-ess-directory nil)
(org-babel-do-load-languages 'org-babel-load-languages '((stata . t)))
