(require 'org)
(require 'ess-site)
(require 'ess-stata-mode)
(add-to-list 'load-path "/home/chl/Documents/notes")
(require 'ox-bibtex)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((stata . t)))

(setq ess-ask-for-ess-directory nil)

(setq org-bibtex-file "/home/chl/Documents/notes/references.bib"
      org-confirm-babel-evaluate nil
      org-export-with-author nil
      org-export-with-creator nil
      org-export-with-toc nil
      org-export-with-tags nil
      org-export-with-section-numbers nil
      org-html-postamble "Generated by %c on %T (%e)"
      org-html-htmlize-output-type nil
      org-html-doctype "html5"
      org-html-head "<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/worg.css\" />"
      org-html-head-include-default-style nil
      org-html-head-include-scripts nil
      org-latex-default-class "tufte-handout"
      org-latex-pdf-process '("latexmk -xelatex -bibtex-cond -f -outdir=%o %f"))

(eval-after-load "ox-latex"
  '(add-to-list 'org-latex-classes
                '("tufte-handout"
                  "\\documentclass[nobib,nofonts]{tufte-handout}
                   \\usepackage{unicode-math}
                   \\usepackage{fontspec}
                   \\setmainfont[Ligatures={TeX,Common}]{Minion Pro}
                   \\setmathfont[Scale=MatchLowercase]{STIX Two Math}
                   \\setsansfont[Scale=MatchLowercase]{Myriad Pro Condensed}
                   \\setmonofont[Scale=MatchLowercase,Numbers=Lining,BoldFont=Fira Code Medium,Contextuals=Alternate]{Iosevka Light Nerd Font Complete Mono}
                   % HACK: Handle broken title when using xelatex
                   \\ifxetex
                      \\newcommand{\\textls}[2][5]{%
                        \\begingroup\\addfontfeatures{LetterSpace=#1}#2\\endgroup
                      }
                      \\renewcommand{\\allcapsspacing}[1]{\\textls[15]{#1}}
                      \\renewcommand{\\smallcapsspacing}[1]{\\textls[10]{#1}}
                      \\renewcommand{\\allcaps}[1]{\\textls[15]{\\MakeTextUppercase{#1}}}
                      \\renewcommand{\\smallcaps}[1]{\\smallcapsspacing{\\scshape\\MakeTextLowercase{#1}}}
                      \\renewcommand{\\textsc}[1]{\\smallcapsspacing{\\textsmallcaps{#1}}}
                   \\fi
                   \\usepackage[backend=bibtex,style=numeric-comp,citestyle=numeric-comp,autocite=plain]{biblatex}
                   \\addbibresource{/home/chl/Documents/notes/references.bib}
                   \\usepackage{booktabs}
                   % HACK: tabular only environment
                   \\setlength{\\doublerulesep}{\\arrayrulewidth}
                   \\let\\tbl\\tabular
                   \\def\\tabular{\\sffamily\\small\\tbl}
                   \\usepackage{graphicx}
                   \\usepackage{hyphenat}
                   \\usepackage{marginfix}
                   \\usepackage{amsmath}
                   \\usepackage{morefloats}
                   \\usepackage{xspace}
                   \\usepackage{nicefrac}
                   \\usepackage{units}
                   \\usepackage{soul}
                   \\usepackage{xcolor}
                   \\usepackage{hyperref}
                   \\hypersetup{colorlinks,allcolors=darkgray}
                   \\makeatletter
                   \\renewcommand*\\verbatim@nolig@list{} % Empty the no-ligature list
                   \\patchcmd{\\hyper@link@}
                     {{\\Hy@tempb}{#4}}
                     {{\\Hy@tempb}{\\ul{#4}}}
                     {}{}
                   \\let\\old@rule\\@rule
                   \\def\\@rule[#1]#2#3{\\textcolor{lightgray}{\\old@rule[#1]{#2}{#3}}}
                   \\makeatother
                   \\newcommand{\\ruler}[1]{\\noindent\\rule[#15pt]{\\linewidth}{0.4pt}}
                   [NO-DEFAULT-PACKAGES]
                   [EXTRA]"
                  ("\\section{%s}" . "\\section*{%s}")
                  ("\\subsection{%s}" . "\\subsection*{%s}")
                  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                  ("\\paragraph{%s}" . "\\paragraph*{%s}")
                  ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))


(eval-after-load "ox-latex"
  '(add-to-list 'org-latex-packages-alist
                '("AUTO" "babel" t ("pdflatex"))))
(eval-after-load "ox-latex"
  '(add-to-list 'org-latex-packages-alist
                '("AUTO" "polyglossia" t ("xelatex" "lualatex"))))
(eval-after-load "ox-latex"
  '(add-to-list 'org-latex-packages-alist '("autostyle=true" "csquotes")))
